---
- name: Deploying A Laravel Application
  hosts: root@161.35.165.17
  become: yes
  become_user: root
  tasks:
  - name: apt update -y
    shell: apt update -y

  - name: Install wget git curl apache
    apt:
      name:
        - wget
        - git
        - curl
        - apache2

  - name: Copy PostgreSQL Script to Install and configure it
    copy:
      src: /home/miracool/Alt-school-related/exam-project/postgres.sh
      dest: ~/postgres.sh
      mode: '0775'
      owner: root

  - name: Run PostgreSQL Script to Install and configure it
    command: sh ~/postgres.sh

  - name: getting packages for php
    shell: wget -qO - https://packages.sury.org/php/apt.gpg | sudo apt-key add -

  - name: move packages to apt repository 
    shell: echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/sury-php.list
  
  - name: apt update 
    shell: apt update -y
  
  - name: installing php
    apt: 
      name: php8.0

  - name: Install other PHP Modules
    apt:
     name:
     - php8.0-cli 
     - php8.0-common 
     - php8.0-pgsql 
     - php8.0-mysql 
     - php8.0-zip 
     - php8.0-gd 
     - php8.0-mbstring
     - php8.0-curl 
     - php8.0-xml 
     - php8.0-bcmath

  - name: Download Composer Installer
    command: curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
  - name: Verify Installation Script is Safe to Run
    command: php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - name: Install Composer Globally
    command: sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  - name: Give Execute Permission for Composer
    file:
      path: /usr/local/bin/composer
      mode: u+x

  - name: delete altlaravel folder if it exists before
    file:
      state: absent
      path: /var/www/laravelapp

  - name: Clone The Laravel Repo
    command: git clone https://github.com/f1amy/laravel-realworld-example-app.git /var/www/laravelapp

  - name: Download and installs all libs and dependencies outlined in the /var/www/laravelapp/composer.lock
    shell: |
      "echo $COMPOSER_ALLOW_SUPERUSER"
      composer install 
    args:
      chdir: /var/www/laravelapp
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1

  - name: Change Ownership To be Assigned to Web Servers
    file:
      path: /var/www/laravelapp
      state: directory
      recurse: yes

  - name: Change the Mode of the Storage Folder
    file:
      path: /var/www/laravelapp/storage
      state: directory
      recurse: yes
      mode: '0775'

  - name: Change the Mode of the Cache Folder
    file:
      path: /var/www/laravelapp/bootstrap/cache
      state: directory
      recurse: yes
      mode: '0775'

  - name: Copy The .env You Have Configured
    copy:
      src: /home/miracool/Alt-school-related/exam-project/.env
      dest: /var/www/laravelapp
      mode: '0775'


  - name: Set the App Key in your .env file # By default, this command is run following a composer create-project, but lets just confirm
    command: php /var/www/laravelapp/artisan key:generate

  - name: Give Application Speed Boost
    command: php /var/www/laravelapp/artisan config:cache

  - name: Install Our pgsql Database
    command: php /var/www/laravelapp/artisan migrate:fresh

  - name: Uncomment the route so the default page opens
    copy:
      src: /home/miracool/Alt-school-related/exam-project/web.php
      dest: /var/www/laravelapp/routes
      mode: '0775'
  - name: Change the Mode of the web.php file so it can also be in the www-data
    file:
      path: /var/www/laravelapp/routes/web.php
      state: file
      owner: www-data
      group: www-data
      mode: '0775'

  - name: Create Our Application Configuration File That will display our page
    copy:
      src: /home/miracool/Alt-school-related/exam-project/laravelapp.conf
      dest: /etc/apache2/sites-available/laravelapp.conf
      owner: root
      group: root
      mode: '0644'

  - name: change laravel permissions
    shell: |
      chown -R :www-data /var/www/laravelapp
      chmod -R 775 /var/www/laravelapp
      chmod -R 775 /var/www/laravelapp/storage
      chmod -R 775 /var/www/laravelapp/bootstrap/cache
          
  - name: Disable the default apache web page
    shell: |
      a2dissite 000-default.conf
      a2enmod rewrite
      a2ensite laravelapp.conf
    args:
      chdir: /etc/apache2/sites-available/

  - name: Restart apache
    service:
       name: apache2
       state: restarted